// Generated by CoffeeScript 1.6.1
(function() {
  var getLang, makeFencer, method, name, _ref;

  getLang = function(file) {
    var ext;
    if (/\.(litcoffee|coffee\.md)$/.test(file)) {
      return 'coffeescript';
    }
    ext = file.match(/(\.(\w+))?\.(md)/);
    if (ext != null ? ext[1] : void 0) {
      return ext[2];
    } else {
      return '';
    }
  };

  makeFencer = function(lang) {
    if (lang == null) {
      lang = '';
    }
    return function(data) {
      var asFenced, indented, text;
      text = data.toString();
      indented = /\n\n    ([\s\S]*?)\n\n(?!    )/mg;
      asFenced = function(match, code) {
        var dedented;
        dedented = code.replace(/^    /mg, '');
        return "\n\n```" + lang + "\n" + dedented + "\n```\n";
      };
      return text.replace(indented, asFenced);
    };
  };

  _ref = {
    getLang: getLang,
    makeFencer: makeFencer
  };
  for (name in _ref) {
    method = _ref[name];
    exports[name] = method;
  }

}).call(this);
